{% set version = "1.1.1" %}

package:
  name: datazets
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datazets/datazets-{{ version }}.tar.gz
  sha256: ea27ddace19bfc9b16d739c0cbb2a05696d3873dd90c574685aa5f5db72e83d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - pandas
    - python >={{ python_min }}
    - requests

test:
  imports:
    - datazets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erdogant/datazets
  summary: Datazets is a python package to import well known example data sets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
